; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:xiaoblesense_arduinocore_mbed]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
framework = arduino
board = xiaoblesense
debug_tool = jlink
upload_protocol = jlink
platform_packages =
    platformio/tool-openocd@^3.1200.0
    platformio/toolchain-gccarmnoneeabi@~1.140201.0
lib_deps =
    ArduinoBLE
    hideakitai/ArduinoEigen
build_flags =
    -Iinclude/ArduinoEigen
    -Iinclude/ArxTypeTraits
    -Iinclude/autoc/include
    -Ofast
    -ffast-math
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16

build_src_filter =
    +<*>
    +<../include/autoc/src/nn/evaluator.cc>
    +<../include/autoc/src/eval/sensor_math.cc>
    +<../generated/*>

[env:xiaoble_arduinocore_mbed]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
framework = arduino
board = xiaoble
debug_tool = jlink
upload_protocol = jlink
platform_packages =
    platformio/tool-openocd@^3.1200.0
    platformio/toolchain-gccarmnoneeabi@~1.140201.0
lib_deps =
    ArduinoBLE
    hideakitai/ArduinoEigen
build_flags =
    -Iinclude/ArduinoEigen
    -Iinclude/ArxTypeTraits
    -Iinclude/autoc/include
    -Ofast
    -ffast-math
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16

build_src_filter =
    +<*>
    +<../include/autoc/src/nn/evaluator.cc>
    +<../include/autoc/src/eval/sensor_math.cc>
    +<../generated/*>
