#ifndef GP_PROGRAM_H
#define GP_PROGRAM_H

#include "GP/autoc/gp_evaluator_portable.h"

// Generated GP evaluator function
// This function is generated by bytecode2cpp and implemented in gp_program_generated.cpp
double generatedGPProgram(PathProvider& pathProvider, AircraftState& aircraftState, double arg);

#endif