#ifndef NN_PROGRAM_H
#define NN_PROGRAM_H

#include <autoc/nn/evaluator.h>
#include <autoc/eval/sensor_math.h>

// Generated NN evaluator function
// This function is generated by nn2cpp and implemented in nn_program_generated.cpp
gp_scalar generatedNNProgram(PathProvider& pathProvider, AircraftState& aircraftState, gp_scalar arg);

// NN program source identifier (weight file path or S3 key) for logging
extern const char* generatedNNProgramSource;

#endif
